import { h, defineComponent } from 'vue'
import TroisCanvas from './TroisCanvas.vue'

const createComponent = (tag: string) =>
    defineComponent({
        inheritAttrs: false,
        name: tag,
        render() {
            return h(tag, this.$attrs, this.$slots?.default?.() || [])
        }
    })

const autoGeneratedComponents = [
    'mesh',
    'sphereBufferGeometry',
    'meshStandardMaterial'
].map(createComponent).reduce((acc, curr) => {
    acc[curr.name] = curr
    return acc
})



export const components = {
    ...autoGeneratedComponents,
    TroisCanvas
}